import logo from './images/logo192.png';
export const examples = [
   {title:'First', pics: [logo], summary:'This is the summary', parts:[['Title','<div> Content for this part </div>'],['Problem','Understanding the problem'],['Goal','We need to make content that looks good.']]},
   {title:'DigiArcade SI 669',pics:[require('./images/1.png'),require('./images/2.png'),require('./images/3.png'),require('./images/4.png'),require('./images/5.png')], summary:'Make a mobile application with React Native', 
      parts:[
         ['Goal','Make a mobile app that works across platforms users can play at their own pace'],
         ['Problem','I had to make a skeleton that would allow my other groupmates to use the same code to let users play different games.'],
         ['Solution','We let the code in the app read the state object that was stored for each individual game. All the game logic would be held in the app and things like turn and points would be saved in Google Firebase allowing for async games.']   
   ]},
   {title:'CCHS Orientation SI 699', pics:[logo], summary:'A client based student project, we had to develop an app that would allow students to do orientation online where the administrator could track progress', parts:[['Goal', 'Create an app for the client that the administrator could easily update as course content changes.'],['Problem', 'The administrator was not very tech savvy and needed a simple way to update the app without having to recode everything from scratch.'],['Context','City Charter High School is unique in the way that it prepares students for the real world. There are certain rules that are distinct from other high schools that they want to make sure both parents and students understand. They needed a way to get families that were not able to learn the material at orientation so that the students would still have all the information they needed to be successful in school.'],['Research','We conducted interviews initially to understand more about what students and parents needed from the app. Then when we had our first prototype we did usability tests on both mobile and desktop views.'], ['Findings','Our usability tests helped us to understand the tech level of our user base and we were able to move things around in the app to make them easier to find. We were also able to fiand and fix bugs before we handed it off to our client.'],['Solution','Throughtout 4 sprints using agile development, we were able to create a functional app using AWS Amplify. Users can log into the app and see their progress on the home page. They can change the language as desired. After taking the quiz they will be marked completed for each module. The administrator also had their own view where they could see the progress of each person.']]}
]