export const examples = [
   {title:'About Me', pics: [require('./images/p1.jpg'),require('./images/p2.jpg'),require('./images/p3.jpg')], summary:`Manager with 5 years of experience leading teams of 3 to 8 personnel. Transitioning into tech with a focus on agile user centered web development.`, parts:[
      ['Undergrad',`I received my bachelors from Purdue University in Human Services. I did a lot of volunteer work and internships with Habitat for Humanity, CANI, Boys and Girls Club and a lot of smaller functions while I was in Fort Wayne. I have always cared about people and am very empathetic. After graduation I prioritized living with friends and family to help support them through changes they were dealing with. I always knew I wanted to go back to school to continue my education and decided on the Air Force in order to limit my student loans.`],
      ['Air Force','I joined the Air Force to do Medical Logistics. My supervisors gave me a lot of responsibilities from the beginning because they knew I could handle it. I trained 20+ people while I was there and was often the point person for projects even though I was new. I made promotion the first time testing and started officially supervising with 7 troops. I received several awards during my time there and also supported and helped my troops get recognized for their accomplishments.'],
      ['Why Information?','While in the Air Force I trained and supervised a lot of people. We worked with a database but few people actually understood it and how it worked. I was able to learn a lot about how people interact with technology when they have different kinds of backgrounds. I helped improve a lot of our systems that let us do our routine tasks better with more transparency. It led me to learn that a system works best if the people using it can understand it.'],
      ['Graduate School','I always enjoyed helping people when they had a problem but I felt more accomplished when I was able to make tools that people understood so that they didn`t have problems. I found the program at Michigan University that would help me enter the tech field while focusing on user interactions. I had some prior experience with programming but the school gave me opportunities to learn more. The program emphasizes teamwork which allowed us to not only see how people use technology, but understand how people from different backgrounds approach making these tech systems.']]},
   {title:'DigiArcade SI 669',links:[['https://github.com/SI669-classroom/si-669-final-project-teamarc','GitHub']],pics:[require('./images/1.png'),require('./images/3.png'),require('./images/7.png'),require('./images/6.png'),require('./images/5.png')], summary:'Make a mobile application with React Native', 
      parts:[
         ['Goal','Make a mobile app that works across platforms users can play at their own pace. We used React Native and Google Firebase.'],
         ['Problem','I led the project with two other classmates. We decided to each make one game for the app and I did the Dots and Boxes game. I had to make a skeleton that would allow my other groupmates to use the same code to let users play different games. I wanted to keep the code as concise as possible.'],
         ['Solution','We let the code in the app read the state object that was stored for each individual game. All the game logic would be held in the app and things like turn and points would be saved in Google Firebase allowing for async games. We setup the Firebase so that the state could be updated by the game in the app. The app loads in the games the user is playing and then in each game it loads in the state of the game but all the games use the same get and update commands to edit their respective states in Firebase using destructuring.']   
   ]},
   {title:'CCHS Orientation SI 699', links:[['https://si-699-school.webflow.io/','Article'],['https://github.com/matthha/react-amp','GitHub']],pics:[require('./images/c1.png'),require('./images/c2.png'),require('./images/c3.png')], summary:'A client based student project, we had to develop an app that would allow students to do orientation online where the administrator could track progress', parts:[
      ['Goal', 'Create an app for the client that the administrator could easily update as course content changes.'],
      ['Problem', 'The administrator was not experienced with web development and needed a simple way to update the app without having to recode everything from scratch.'],
      ['Context','City Charter High School is unique in the way that it prepares students for the real world. There are certain rules that are distinct from other high schools that they want to make sure both parents and students understand. They needed a way to get families that were not able to learn the material at orientation so that the students would still have all the information they needed to be successful in school.'],
      ['Research','We conducted interviews initially to understand more about what students and parents needed from the app. Then when we had our first prototype we did usability tests on both mobile and desktop views.'], 
      ['Findings','Our usability tests helped us to understand the tech level of our user base and we were able to move things around in the app to make them easier to find. We were also able to fiand and fix bugs before we handed it off to our client.'],
      ['Solution','Throughtout 4 sprints using agile development, we were able to create a functional app using AWS Amplify. Users can log into the app and see their progress on the home page. They can change the language as desired. After taking the quiz they will be marked completed for each module. The administrator also had their own view where they could see the progress of each person.']]},
   {title:'Mirror Match SI 612', links:[['https://verdant-cell-8ec.notion.site/Mirror-Match-70a30d36bb254905935f71cfe1b112ac','Article']], pics:[require('./images/m1.png'),require('./images/m2.png')], summary:'Design an IoT system informed with user research.', 
      parts:[
         ['Goal','Design an IoT system and prototype that could be implemented and used in the near future. Our team decided to focus on the home environment for 20-30 year olds who would be more inclined to adopt new technology.'],
         ['User Research','We conducted a survey (60+ responses), a diary study, and user enactments. Analysis helped identify top pain points in user`s routines. We were also able to find out that users did not like when technology made decisions on their behalf but rather preferred to receive information and relevant suggestions that they could act upon.'],
         ['Solution','We used figma and made screens in order to Wizard of Oz our prototype for users. We also coded some NeoPixel lights using an Arduino/Photon setup. Our system called Mirror Match helped users get ready in the morning and assisted them with outfit recommendations.']   
   ]},
   {title:'Athena Consulting ENTR 560', pics:[require('./images/a1.png'),require('./images/a2.png'),require('./images/a3.png'),require('./images/a4.png'),require('./images/a5.png')], summary:'Help client improve business procedures and assist site redesign.', 
      parts:[
         ['Goal','Work with client to identify business needs, then propose and implement plan to meet their needs.'],
         ['Problem','After the initial meeting, our team identified the client wanted a better Ecommerce business/presence. They had been using the same site for 8 years and it was due for an overhaul while allowing the business space to grow and expand as needed.'],
         ['Research','Our team identified different platforms they could use to conduct their business operations. We presented the findings and let the client decide which platforms we would use to make the changes.'],
         ['Solution','After client chose what platforms to use (Square), we had to quickly learn about them in order to begin redesigning and restructuring their site for a better customer shopping process. We also provided guidance for how to implement a better inventory process that included the logistics of tracking orders and resupplies. We made a flexible site that was better looking than the original and would allow them to scale it as the business grew.']   
   ]}
]